### ISSUE TITLE
运行代码后 profile 为空

### ISSUE THREAD

**Issue by Allwillcome** [redleafnew/zotero-javascripts#1]
首先谢谢你的这个代码，非常好用实用，但是在运行代码后 data 里有数据，但是 profile 文件夹为空
![image](https://user-images.githubusercontent.com/35840764/121776125-c50aaa00-cbbd-11eb-801b-b0eb736a6bce.png)
难不成是 zotero 测试版本的原因？再次感谢
![image](https://user-images.githubusercontent.com/35840764/121776340-eb7d1500-cbbe-11eb-9f03-11d491847bd4.png)

系统版本为 win10
![image](https://user-images.githubusercontent.com/35840764/121776357-fcc62180-cbbe-11eb-8a06-f2aad4cdc249.png)

**Comment by redleafnew** [comment]
我没有试过测试版，不知道它的profile文件夹是否变了。



Best regards!

Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University 
 
发件人： SportKight
发送时间： 2021-06-12 20:49
收件人： redleafnew/zotero-javascripts
抄送： Subscribed
主题： [redleafnew/zotero-javascripts] 运行代码后 profile 为空 (#1)
首先谢谢你的这个代码，非常好用实用，但是在运行代码后 data 里有数据，但是 profile 文件夹为空

难不成是 zotero 测试版本的原因？再次感谢
系统版本为 win10

**Comment by Allwillcome** [comment]
https://github.com/redleafnew/zotero-javascripts/issues/1#issuecomment-860050437 
那应该就是新版本的 profile 位置改变了。
还是谢谢您！
或许等zotero 测试版本变为稳定版本后，您可以再看下 profile 的情况。

**Comment by redleafnew** [comment]
我今天在最新的beta 版上试，可以备份的，profile和data中都有数据的。

**Comment by Allwillcome** [comment]
那我有时间再试试，谢谢您
